### ISSUE TITLE
Discrepancies between Dockerfiles

### ISSUE THREAD

**Issue by matthewvalimaki** [smebberson/docker-alpine#10]
[alpine-nginx](https://github.com/smebberson/docker-alpine/blob/master/alpine-nginx/Dockerfile) specifies specific nginx version while [alpine-consul-nginx](https://github.com/smebberson/docker-alpine/blob/master/alpine-consul-nginx/Dockerfile) does not.

Version should be specified to avoid potential breakage caused by version changes. Latest non-breaking versions available should be used for releases.

It would be nice to note package version changes in change log :)

**Comment by smebberson** [comment]
@matthewvalimaki, good catch. I'll add this in.

**Comment by smebberson** [comment]
@matthewvalimaki, as of the later versions of these images, this has all been resolved. nginx is now properly pinned.
