### ISSUE TITLE
Add support for consul-template

### ISSUE THREAD

**Issue by matthewvalimaki** [smebberson/docker-alpine#11]
I would recommend adding [consul-template](https://github.com/hashicorp/consul-template) to [alpine-consul-base](https://github.com/smebberson/docker-alpine/tree/master/alpine-consul-base) as it is integral part of Consul itself.
* Templates should be placed in `/etc/consul-template/templates/`.
* A default configuration file should be placed in `/etc/consul-template/conf.d/` defaulting to consul on `127.0.0.1:8500`.
* Actual template configurations should be placed in `/etc/consul-template/conf.d/`.
* s6 service should be provided but with if-clause to check whether `/etc/consul-template/conf.d/` contains template configurations. No need to fire up service that does nothing.

This setup should provide 100% automatic way to enable consul-template when proper configuration exists.

[user-consul-nginx-nodejs](https://github.com/smebberson/docker-alpine/blob/master/examples/user-consul-nginx-nodejs) has nginx [default.conf](https://github.com/smebberson/docker-alpine/blob/master/examples/user-consul-nginx-nodejs/root/etc/nginx/conf.d/default.conf) which should be updated to utilize consul-template with s6 service definition.

If this proposition is supported I can work on the pull request.

**Comment by matthewvalimaki** [comment]
A note:
All additional user added templates should be placed in sub folders of `/etc/consul-template/templates/` to support VOLUME (for example `VOLUME /etc/consul-template/my-test-templates`). Reason for this is: suppose one has a data container with templates and if `VOLUME /etc/consul-template` were done base image templates, if any, would stop working. Using a sub folder should not be a problem because templates can be declared individually, for example: `consul-template -template "/etc/consul-template/my-test-templates/nginx.ctmpl:/etc/nginx/conf.d/default.conf"`.

**Comment by smebberson** [comment]
@matthewvalimaki, this will be a great addition! A PR would be fantastic. Thanks for offering to do the work. I agree with everything you've written above. Let me know if you need a hand.
