### ISSUE TITLE
Unnecessary files in alpine-consul-ui

### ISSUE THREAD

**Issue by matthewvalimaki** [smebberson/docker-alpine#16]
https://github.com/smebberson/docker-alpine/blob/master/alpine-consul-ui/root/etc/cont-finish.d/00-consul and https://github.com/smebberson/docker-alpine/blob/master/alpine-consul-ui/root/etc/services.d/consul/run seem to be unnecessary as the base image contains exact same files.

**Comment by smebberson** [comment]
Closing as this was tidied up in recent releases.
