### ISSUE TITLE
Update Consul to v0.6.3

### ISSUE THREAD

**Issue by matthewvalimaki** [smebberson/docker-alpine#19]
See https://github.com/hashicorp/consul/blob/master/CHANGELOG.md and https://www.consul.io/docs/upgrade-specific.html.

Couple highlights important for us:
* TCP health check
* Sending telemetry (I see `alpine-consul-statsd` or similar coming)

Some breakage will happen:
* Data storage changes
* Web UI structure updated a bit

**Comment by smebberson** [comment]
@matthewvalimaki, sounds good. I'll work this in once we have #13 merged in.

**Comment by matthewvalimaki** [comment]
Related PRs: #28 and #29.

Note: since Consul 0.6.0 the AMD64 bin version works so no need to compile ourselves.

**Comment by smebberson** [comment]
PR #34 incorporates these changes. It's nice not having to build Consul anymore! Please note, I didn't make any changes regarding the UI yet, please see #30 regarding some questions on this.

Also, I didn't do anything specific regarding incompatibility. I think this should be handled downstream as needed.
