### ISSUE TITLE
Incorrect shell set for consul and rabbitmq users

### ISSUE THREAD

**Issue by matthewvalimaki** [smebberson/docker-alpine#22]
New users are created for `alpine-consul` and `alpine-rabbitmq`. While these accounts do work `su - consul` resulted in ```su: can't execute ':60:60:mysql:/var/lib/mysq': No such file or directory```, see
![wrong shell](https://cloud.githubusercontent.com/assets/1033909/12201926/d2ddcebc-b5db-11e5-8a3e-807133728495.JPG). So new users defaulted to mysql for whatever reason. While I do not want to `su - consul` for any legitimate reason having a wrong shell is still a problem. This can be easily fixed by adding `-s /bin/sh` to the `adduser` command.

**Comment by smebberson** [comment]
@matthewvalimaki, this would be a great fix. That stupid issue plagued me! I'll work on it once I get this repo in shape.

**Comment by smebberson** [comment]
As a result of PR #34, this has been fixed alpine-consul. alpine-rabbitmq will be coming soon :)

**Comment by smebberson** [comment]
As a result of the latest commits, this has now been fixed in alpine-rabbitmq.
