### ISSUE TITLE
Improving DNS resolution

### ISSUE THREAD

**Issue by smebberson** [smebberson/docker-alpine#24]
It turns out, [DNS resolution on Alpine Linux isn't complete](https://github.com/janeczku/docker-alpine-kubernetes#motivation).

I've recently run into this issue while moving away from IP-based services connection to hostname-based services connection (i.e. connecting to Redis on another container within Node.js), on Tutum.

I'm thinking of using [go-dnsmasq](https://github.com/janeczku/go-dnsmasq) to resolve the problem, as is demonstrated here: https://github.com/janeczku/docker-alpine-kubernetes/tree/master/versions/3.2. This would go into `alpine-base`.

**Comment by smebberson** [comment]
@matthewvalimaki, could I get your thoughts here?

**Comment by matthewvalimaki** [comment]
@smebberson I do not have strong opinion on this matter other than that I do have a need for dnsmasq in the near future :) Only thing that I wonder right now is if Consul dns interface could be used instead or in conjunction.

**Comment by smebberson** [comment]
@matthewvalimaki, based on a quick read of https://www.consul.io/docs/agent/dns.html, I don't think it is suitable. You need to specify a `recursors` configuration for the Consul DNS interface in order for it to resolve queries outside of the "consul." domain.

If you have no objections, I might put something together and add this to `alpine-base`.

**Comment by matthewvalimaki** [comment]
@smebberson no objections.

I wonder though if consul should be made primary dns with recursors
pointing to dnsmasq which then in the end points to real dns. I have no use
case for this now, but I do not see immediate downside for this and it
would offer easier access to consul.

Whatever you end up deciding works for me. We can always adjust later.

**Comment by smebberson** [comment]
@matthewvalimaki I've released [alpine-base v1.2.1](https://github.com/smebberson/docker-alpine/blob/master/alpine-base/VERSIONS.md) to resolve this issue.
