### ISSUE TITLE
Consul HTTP API port not exposed

### ISSUE THREAD

**Issue by matthewvalimaki** [smebberson/docker-alpine#30]
`alpine-consul` should expose the default Consul HTTP API port 8500/tcp.

A side note: `alpine-consul-ui` is obsolete once we do #19 as the ui is now part of the Consul itself. The ui would be accessible via http://localhost:8500/ui.

**Comment by matthewvalimaki** [comment]
Furthermore it seems that the HTTP API is not available at all outside of the container because `-client` defaults to `127.0.0.1`.

I recommend `/etc/services.d/consul/run` is modified to contain `-client ${BIND}` to make HTTP API exposed outside of the container. Or the very least this should be mentioned in the documents so that when needed images could be extended properly.

**Comment by smebberson** [comment]
As a result of PR #34, 8500/tcp is now exposed.

However, during testing of #34 I'm not sure that Consul's UI is bundled within Consul itself. I couldn't find it on their change long and their website still links to a seperate download for the UI.

Am I missing something here?

**Comment by smebberson** [comment]
Closing as this is all fixed.
