### ISSUE TITLE
Does go-dnsmasq need root?

### ISSUE THREAD

**Issue by matthewvalimaki** [smebberson/docker-alpine#32]
Does `go-dnsmasq` need to be run as root? I do get that it needs to be able to modify `-rw-r--r--    1 root     root           239 Mar 14 21:57 /etc/resolv.conf` but that could be taken care of with a new group?

I can work on PR if root is not required.

**Comment by smebberson** [comment]
@matthewvalimaki, I'm not aware that it needs to be run as root. The repository doesn't mention anything about it and I have not ever tried to not run as root. Sorry I couldn't be of more help here. I guess you'll have to give it a shot ;)

**Comment by smebberson** [comment]
@matthewvalimaki, are you interesting in creating a PR for this?

**Comment by matthewvalimaki** [comment]
@smebberson PR put through but make sure build environment is enough up to date due to kernel bug causing build to fail :(
