### ISSUE TITLE
Project stagnated (we're getting back on track)

### ISSUE THREAD

**Issue by matthewvalimaki** [smebberson/docker-alpine#36]
@smebberson I'm concerned that this project has come to a halt. We have outdated base images, old ca-certificates, PRs etc. I do not want to fork either.

I propose creation of an organization or something which allows myself to merge, tag and release (I assume Docker Hub is updated automatically with releases). You would still be the owner.

To further improve common goals and communication I would:
- Have a road map and change log
- Do beta releases
- Implement tests

**Comment by smebberson** [comment]
@matthewvalimaki, I hear your concern and it's fair enough. The state of this repository and its images could be better.

I'm not quite yet ready to create an organisation for them, although, I see that as being best fit for the project in the not too distant future. I'm not ready for that just yet though.

Here is what I'm proposing:

- I'll version 1.0.0 every image that isn't versioned at the moment (complete with documentation).
- I'll go through the PRs and update base images, and then all downstream images accordingly.
- I'll then address the issues.

(Give me a week to get through this, there is quite a bit there.)

In the meantime, could you please submit an issue on each of the above goals you've listed so that we can collaborate more closely on it (in particular I've been searching and thinking of ways to test these images appropriate but haven't found much at all yet, any insight you have would be great to hear). Let's aim towards this becoming an organisation and you a core member.

@matthewvalimaki, what do you think? Is this an okay first step in the direction you're wanting?

**Comment by matthewvalimaki** [comment]
@smebberson I think your feedback is good :) You've done well with maintaining this repository, the images and fixed issues I've introduced in my PRs. Even with the current state of the images they're the best :)

Really my goal is to get up-to-date images and while I do not expect immediate reaction to issues or PRs I would prefer some response within a week or so. This is to set expectations. So whether or not there is just you or an organization does not matter in the end. Only reason why I recommended shared responsibilities was to alleviate pressure from you.

I'll do as you suggested and create issues for the goals I mentioned.

**Comment by smebberson** [comment]
@matthewvalimaki, thanks for getting back to me. I have the same goal as you, I would like to be more responsive too and will aim to be.

I think it would be great if we form an organisation together for the future of this repository. Let's work a little more closely on the next round of issues you'll open and post that, we'll aim for an organisation. I think that would be great.

**Comment by smebberson** [comment]
[alpine-consul-redis](https://github.com/smebberson/docker-alpine/blob/master/alpine-consul-redis/VERSIONS.md) is now at [v1.0.0](https://hub.docker.com/r/smebberson/alpine-consul-redis/tags/).

**Comment by smebberson** [comment]
[alpine-consul-ui](https://github.com/smebberson/docker-alpine/tree/master/alpine-consul-ui) is now at [v1.0.0](https://hub.docker.com/r/smebberson/alpine-consul-ui/tags/).

**Comment by smebberson** [comment]
[alpine-redis](https://github.com/smebberson/docker-alpine/tree/master/alpine-redis) is now at [v1.0.0](https://hub.docker.com/r/smebberson/alpine-redis/tags/).

This marks the first dot-point as one. Onto the next task, updating the base images. Then onto the remaining PRs.

**Comment by matthewvalimaki** [comment]
Awesome!

**Comment by matthewvalimaki** [comment]
@smebberson #37 added for "Have a road map and change log".

**Comment by smebberson** [comment]
[alpine-base](https://github.com/smebberson/docker-alpine/tree/master/alpine-base) is now at [v2.0.0](https://hub.docker.com/r/smebberson/alpine-base/tags/)

**Comment by smebberson** [comment]
[alpine-apache](https://github.com/smebberson/docker-alpine/tree/master/alpine-apache) is now at [v2.0.0](https://hub.docker.com/r/smebberson/alpine-apache/tags/)

**Comment by smebberson** [comment]
[alpine-consul](https://github.com/smebberson/docker-alpine/tree/master/alpine-consul) is now at [v2.0.0](https://hub.docker.com/r/smebberson/alpine-consul/tags/)

**Comment by smebberson** [comment]
[alpine-consul-base](https://github.com/smebberson/docker-alpine/tree/master/alpine-consul-base) is now at [v3.0.0](https://hub.docker.com/r/smebberson/alpine-consul-base/tags/)

**Comment by smebberson** [comment]
[alpine-confd](https://github.com/smebberson/docker-alpine/tree/master/alpine-confd) is now at [v2.0.0](https://hub.docker.com/r/smebberson/alpine-confd/tags/)

**Comment by smebberson** [comment]
[alpine-rabbitmq](https://github.com/smebberson/docker-alpine/tree/master/alpine-rabbitmq) is now at [v2.1.1](https://hub.docker.com/r/smebberson/alpine-rabbitmq/tags/), but I also created v2.0.0, v2.1.0. See https://github.com/smebberson/docker-alpine/blob/master/alpine-rabbitmq/VERSIONS.md

**Comment by smebberson** [comment]
@matthewvalimaki could you please take a look at this [new branch](https://github.com/smebberson/docker-alpine/tree/alpine-consul-ui-upgrades) I've been working on? Specifically the [CHANGELOG](https://github.com/smebberson/docker-alpine/blob/alpine-consul-ui-upgrades/CHANGELOG.md).

While upgrading _alpine-consul-ui_ I discovered that as a result of the Consul upgrade, Consul-related images were not leaving the cluster correctly (when the container was stopped via `CTRL+C`). There has also always been a few little annoying issues with the way containers were brought down causing various error messages to appear. I decided to jump right in and fix those.

The branch I linked to is the first step. But it has come a long way. Everything works a little more cleanly now and everything exits more cleanly too (there is still some work to be done). The CHANGELOG documents everything (I don't intend to keep this around, but move them into the VERSIONS file for each image).

I've also added a complete example, which shows how to use all of these images for a complete setup using Docker with microservices and service discovery via Consul. Take a look at https://github.com/smebberson/docker-alpine/tree/alpine-consul-ui-upgrades/examples/complete.

@matthewvalimaki, I'm hoping you can test everything out to make sure it is working for you too. And for your general feedback on the changes. And specifically, referring to https://github.com/smebberson/docker-alpine/blob/alpine-consul-ui-upgrades/examples/complete/docker-compose.yml and the `conductor`, `consul` and `consul2` containers - is that how you bootstrap a Consul cluster?

**Comment by smebberson** [comment]
@matthewvalimaki, @sandytrinh, that branch has now been updated to allow zero-conf Consul bootstrapping! Checkout the [CHANGELOG](https://github.com/smebberson/docker-alpine/blob/alpine-consul-ui-upgrades/CHANGELOG.md) and updated [README](https://github.com/smebberson/docker-alpine/tree/alpine-consul-ui-upgrades/examples/complete).

**Comment by matthewvalimaki** [comment]
@smebberson apologies for delayed response. But man do the changes look good. I'll be testing tonight. I love the CHANGELOG - it is awesome. While it is a lot of work to write it all out as consumer I appreciate the fact that changes with explanations and effects are there. With Dockerfile I've taken the habit of reading changelogs more than ever before. Probably because with containers maintainers, such as you, are now responsible for dependencies and not some packaging system.

> There has also always been a few little annoying issues with the way containers were brought down causing various error messages to appear. I decided to jump right in and fix those.

Did it take care of #21 as well?

> I'm hoping you can test everything out to make sure it is working for you too. And for your general feedback on the changes.

I will test tonight.

> is that how you bootstrap a Consul cluster?

I do not have a cluster setup anywhere right now, been going with single instance. I'll have to play around with clustering but that'll take more time.

**Comment by smebberson** [comment]
@matthewvalimaki, yep, it resolved #21. Well, bootstrapping a Consul cluster (on the same host machine) is SUPER simple now. Super simple. Make sure you read https://github.com/smebberson/docker-alpine/tree/alpine-consul-ui-upgrades/examples/complete it details the new 'complete' example (although not finished yet, I want to put Node.js and redis in there too) showing how they all hang together. @sandytrinh has reviewed the new zero-conf setup and likes it. So if you do too (@matthewvalimaki), I'll update all Consul-related containers to use this new method by default. The new method does bring a requirement for Docker 1.10+ though, so I was thinking of enabling backward compatibility by supporting usage of `links` to link other Consul containers to form a cluster.

**Comment by smebberson** [comment]
@matthewvalimaki, made some more changes to better support the embedded DNS server in Docker 1.10+ (https://github.com/smebberson/docker-alpine/blob/alpine-consul-ui-upgrades/CHANGELOG.md).

To test all of these changes, you'll now need to build the following, before building the containers in `examples/complete`:

- `alpine-base`
- `alpine-consul`
- `alpine-consul-base`
- `alpine-consul-nginx`
- `alpine-consul-ui`

**Comment by smebberson** [comment]
@matthewvalimaki, just wanted to let you know that tomorrow I'm going to go and forge ahead with the release of the consul based containers with these updates. I would have liked to get your opinion, but I understand you're busy. I really want to get them out so that people can see these images are still a viable and worthwhile option. Please there are some critical updates I want to release such as Nginx (HTTP/2) and Node.js 6. If you could squeeze in a quick check and opinion, that'd be great, otherwise I'll release anyway and hopefully have done it all justice.

**Comment by ncornag** [comment]
+1

**Comment by sandytrinh** [comment]
@smebberson Really looking forward to these new images tomorrow! Perfect timing for my new project :)

**Comment by matthewvalimaki** [comment]
@smebberson looks good to me! I'm exclusively using your images (many of them) and do appreciate the work.

**Comment by matthewvalimaki** [comment]
@smebberson if you can throw in latest `go-dnsmasq` as the version you're currently using is one release old ;)

**Comment by smebberson** [comment]
@matthewvalimaki I think I've already got the latest version in there? https://github.com/smebberson/docker-alpine/blob/alpine-consul-ui-upgrades/alpine-base/Dockerfile

**Comment by matthewvalimaki** [comment]
@smebberson you are correct. I was looking at some other repository with `1.0.4`. Good stuff.

**Comment by smebberson** [comment]
@ncornag and @matthewvalimaki I've just made a few more changes. @ncornag all of your suggestions have been included - hopefully this makes these images work better with Rancher. Could you two please test and report back? All of the changes that I'm wanting to make have been made and it's just a matter of testing to make sure everything is all good and then I can release. If you could spare some time to test and report back, that'd be very much appreciated. Thanks!

**Comment by smebberson** [comment]
To make sure everything is clean before testing, run `./alpine-base/build && ./alpine-consul/build && ./alpine-consul-base/build && ./alpine-consul-nginx/build && ./alpine-consul-ui/build && ./alpine-consul-nodejs/build` to rebuild all of the images and then `dc build` to rebuild the example images inheriting from the local updates. Good luck ;)

**Comment by ncornag** [comment]
I ran the "complete" example via the provided `docker-compose.yml` and all is going ok.
I also test it successfully in a rancher.io environment, changing only the `container-ip` to meet my requirements. I will copy here the script for future reference:
```shell
#!/usr/bin/with-contenv sh

if getent hosts rancher-metadata > /dev/null; then
  if test -z $1; then
    curl -s http://rancher-metadata/latest/self/container/primary_ip
  else
    dig +short $1
  fi
else
  dig +short ${1:-$HOSTNAME}
fi
```

**Comment by matthewvalimaki** [comment]
As a note error `dns: error starting tcp server: accept tcp 127.0.0.1:8600: use of closed network connection` is reported here: https://github.com/hashicorp/consul/issues/1320

**Comment by smebberson** [comment]
Closing this as I've released a bunch of major changes.
