### ISSUE TITLE
You can use the alpine package in testing for consul

### ISSUE THREAD

**Issue by neeravkumar** [smebberson/docker-alpine#4]
Hi,

Alpine has recently added a package for consul, its in testing right now:

http://wiki.alpinelinux.org/wiki/User_talk:Jch/consul

So, this might be something you would want to consider.

**Comment by smebberson** [comment]
I will definitely keep an eye on it. Although, it seems as though it might be quite opinionated in it's setup and less flexible perhaps that what we're going for here?

**Comment by neeravkumar** [comment]
That's true, good work on making the whole go install + git checkout an atomic step. I prefer the convenience of OS packages and that is why I wanted to mention it here. 

Maybe your step could be just getting the package and extracting the binary since that is the biggest part of this setup.

**Comment by smebberson** [comment]
Yeah, I agree, I generally prefer OS packages. I did look for one, but
there was nothing at the time. If I had more time, I would teach myself how
to create my own Alpine package and create a dead simple one. But I have no
extra for that at the moment.

I'll definitely keep an eye on it.

**Comment by matthewvalimaki** [comment]
Since Consul version 0.6.0 we do not need to compile it ourselves, the binary provided by HashiCorp for Linux AMD 64 works. I suggest that to be used in the absence of package.

**Comment by smebberson** [comment]
I'm going to close this in favour of #19
