### ISSUE TITLE
Consul join IPs

### ISSUE THREAD

**Issue by ncornag** [smebberson/docker-alpine#44]
The actual `consul-ip` script searches consul IPs to join and returns the first one. I think it is a better solution to give more than one. Sometimes that first consul container is down and the other containers cannot join the cluster.
It could be achieved passing a set of well known IPs, or just everything we found under the `consul` dns name. 
I made the modifications and it works a lot better in situations where the containers go down and up. I will do a pull request for you to review.

**Comment by smebberson** [comment]
Sounds good. A PR would be great. If you could do it against the `alpine-consul-ui-upgrades` branch like you did last time, that'd be great :)

**Comment by smebberson** [comment]
@ncornag this has been taken care of in recent updates to the development branch. Thanks for the suggestion!
