### ISSUE TITLE
Consul advertise and client address

### ISSUE THREAD

**Issue by ncornag** [smebberson/docker-alpine#45]
If you have multiple IPs in your container, it's necessary to add `-advertise $BIND -client 0.0.0.0` to the `run` script to be able to connect to it.
This modification should not cause any side effect if the containers has only one address, but I think you should test it just in case.

**Comment by smebberson** [comment]
Yeah okay, that sounds like a sensible default. I'll change that and see how it goes. Thanks for that pickup.

**Comment by smebberson** [comment]
@ncornag, I've made these changes in the latest commits (https://github.com/smebberson/docker-alpine/blob/alpine-consul-ui-upgrades/alpine-consul/root/etc/services.d/consul/run). They're working well, thanks!
