### ISSUE TITLE
Add ENV for Consul -advertise-wan

### ISSUE THREAD

**Issue by matthewvalimaki** [smebberson/docker-alpine#50]
We should support Consul [-advertise-wan](https://www.consul.io/docs/agent/options.html#_advertise-wan) and [translate_wan_addrs](https://www.consul.io/docs/agent/options.html#translate_wan_addrs) through ENV.

Perhaps introduce `ENV CONSUL_ADVERTISE_WAN=127.0.0.1` and `ENV CONSUL_TRANSLATE_WAN_ADDRS=true` which then are checked in `alpine-consul` `/etc/services.d/consul/run` and used if present.

**Comment by matthewvalimaki** [comment]
As `translate_wan_addrs` is only available via configuration file we would need `cont-init.d` in `alpine-consul`. Perhaps we should add the configuration option with default `false` value and then in `cont-init.d` do simple check if ENV is true and use `sed -i "s/translate_wan_addrs=false/translate_wan_addrs=true/g"`?

**Comment by smebberson** [comment]
@matthewvalimaki I like these ideas.

However, rather than using `sed` in a `cont-init.d` script, why don't we use `consul-template` with the `once` parameter (and take the value from ENV has per your suggestion). I find that sort of stuff is much easier for other contributors/users to work with. It also sets in place an easy spot to further alter configuration for Consul (just add ENV vars in your Dockerfile and update the template).

What do you think?

**Comment by matthewvalimaki** [comment]
@smebberson I do not agree with the idea of using `consul-template` for this. My problem is with what `consul-template` is meant for as described by https://github.com/hashicorp/consul-template:

> This project provides a convenient way to populate values from Consul into the filesystem using the consul-template daemon.

And regarding this:

> It also sets in place an easy spot to further alter configuration for Consul (just add ENV vars in your Dockerfile and update the template).

I do not understand how `consul-template` would make things easier. In both cases ENV needs to be added and either a Consul template file along with configuration file needs to be added or existing `/etc/services.d/consul/run` be updated to support the ENV.

I do agree that as more features are supported more complexity is introduced but I do not know how to get away with it without modifying `consul` to support reading ENV directly. Take our `-domain` as an example. We had to modify `run` to add support for it. It would be nicer for `consul` to check if ENV `CONSUL_DOMAIN` existed and then use it still allowing `-domain` to override it.

**Comment by smebberson** [comment]
@matthewvalimaki Sure, we can run with your suggestion then. That works for me. Are you able to do a PR?

Longer term, what about something crazy like `consul-template` actually spitting out the `/etc/services.d/consul/run` based entirely on environment variables? HAH!

**Comment by smebberson** [comment]
@matthewvalimaki, are you interested in creating a PR for this? I've just released a bunch of improvements across the board to this repo.

**Comment by matthewvalimaki** [comment]
@smebberson took a long time but please take a look at #56.

**Comment by smebberson** [comment]
@matthewvalimaki, this is all merged in. Applied to `alpine-consul-nodejs` and `alpine-consul-nginx` at this stage. Working through the rest as quick as I can.
