### ISSUE TITLE
Outdated Example links

### ISSUE THREAD

**Issue by polarathene** [smebberson/docker-alpine#51]
[alpine-base example](https://github.com/smebberson/docker-alpine/tree/master/alpine-base#example) links to [ubuntu-base](https://hub.docker.com/r/smebberson/nodejs/).

[alpine-consul-nginx-nodejs example](https://github.com/smebberson/docker-alpine/tree/master/alpine-consul-nginx-nodejs#example) links to [Github 404 page](https://github.com/smebberson/docker-alpine/tree/master/examples/alpine-consul-nginx-nodejs). New location is [here](https://github.com/smebberson/docker-alpine/tree/master/examples/user-consul-nginx-nodejs).

There may be more, I've just come across these two while reading through the repo.

**Comment by smebberson** [comment]
Thanks! I've fixed those and a few others I found too.
