### ISSUE TITLE
alpine-consul-apache no has  consul-template

### ISSUE THREAD

**Issue by chuanqi327** [smebberson/docker-alpine#53]
in alpine-consul-apache image no install consul-template ,^_^ @smebberson

**Comment by smebberson** [comment]
@chuanqi327, it needs an upgrade to the latest alpine-base (v3.0.0)... I'll try and make this a priority.

**Comment by smebberson** [comment]
@chuanqi327, I just launched `v2.0.0` of `alpine-consul-apache` which now uses `alpine-base:3.1.0`. So you should have everything you need now. I'll close this issue out.
