### ISSUE TITLE
Remove s6-overlay.tar.gz

### ISSUE THREAD

**Issue by matthewvalimaki** [smebberson/docker-alpine#6]
/tmp/s6-overlay.tar.gz should be deleted once extracted.

**Comment by smebberson** [comment]
Good call. I have some changes for the Node.js images in the works, and I'll update this once they're complete.

**Comment by smebberson** [comment]
@matthewvalimaki, this has been resolved in the latest (alpine-base)[https://github.com/smebberson/docker-alpine/blob/master/alpine-base/Dockerfile].
