### ISSUE TITLE
Update to latest Consul

### ISSUE THREAD

**Issue by matthewvalimaki** [smebberson/docker-alpine#61]
Consul 0.7.0 is out now and we should update to it asap :) I went through the changes and while it does have breakage and new features I did not see anything that affects this project.

My biggest pain point which should be resolved now was the inability to decide on cluster leader after failures.

I also recommend we resolve #50 by merging those changes in at the same time.

**Comment by smebberson** [comment]
@matthewvalimaki, sorry for the late reply here. Good idea, this would be great. Have you tested this, is there any configuration changes we need to make or anything? I'm keen to merge in #56, should I do this before hand?

**Comment by matthewvalimaki** [comment]
@smebberson no problem. I have not tested latest yet. Based on changelog review I do not see any changes we would need to introduce. It should be made clear though that older Consuls will not work with, see the changelog for details.

Regarding #56 there is a related change in latest Consul:
> New translate_wan_addrs behavior from [GH-2118] translates addresses in HTTP responses and could break clients that are expecting local addresses.

So flag that #56 introduces is not necessarily required since by default calls coming from remote dc will automatically now get the remote node address. If I understood things correctly :) In any event I would upgrade Consul and merge in my change with perhaps unnecessary flag.

**Comment by smebberson** [comment]
@matthewvalimaki, all merged in. Closing this issue accordingly.
