### ISSUE TITLE
alpine-base + openjdk

### ISSUE THREAD

**Issue by rbellamy** [smebberson/docker-alpine#62]
I'd like to see an openjdk-based image using `alpine-base`.

My team works with the Play Framework, which is perfectly capable of running in the standard "docker way" - except that the `openjdk/alpine` image doesn't have the s6 overlay, and thus I believe will suffer from the resolv.conf issue, and thus could benefit from the go-dnsmasq functionality you have here.

If there's interest, I will fork and submit a PR.

**Comment by smebberson** [comment]
Hey @rbellamy, that sounds great. I'd like to see something Java related in here. I don't use it much so don't have the expertise but if you're keen to add it, that'd be great.

It is worth noting and considering however that the latest version of Alpine, 3.4, has fixed all of the resolv.conf issues so go-dnsmasq is technically not required anymore.

**Comment by rbellamy** [comment]
Well... that's interesting. I didn't realize that. That's really my forcing function here, so I think I'll put this on the back burner for now. Thanks for the heads-up!

**Comment by smebberson** [comment]
@rbellamy, no worries, I'll close this issue for now but you're welcome to reopen or start a new one should you become interested in this again.

**Comment by rbellamy** [comment]
I'm a bit confused by something I found in https://github.com/nginxinc/docker-nginx/issues/78. Looks to me like the expected fix in v3.4 of alpine hasn't resolved the problem... am I reading that right?
