### ISSUE TITLE
ping: permission denied (are you root?)

### ISSUE THREAD

**Issue by markych96** [smebberson/docker-alpine#65]
Hello!
Is that normal behaviour? what after creating container by command
`docker run -d smebberson/docker-alpine`
and then getting shell by
`docker exec -it [container_id] sh`
and send `ping 172.17.0.1` i've got a error message 
>  ping: permission denied (are you root?)

how can i solve this problem?

P.S. docker version 1.12.1

thank you

**Comment by rbellamy** [comment]
Force `UID=0` (root) when starting the container:
```
docker exec -u 0 -it [container_id] sh
```

**Comment by smebberson** [comment]
@markych96, has @rbellamy helped you out here? Can I close this issue?

**Comment by markych96** [comment]
`-u 0`
not helped
but i think you can close issue, i think that error is caused by alpine os as a docker host system
then i start alpine-s6-overlay on rancher host error was gone

**Comment by smebberson** [comment]
@markych96, okay, thanks.

**Comment by michaeljs1990** [comment]
@smebberson I would like to request that this is reopen. In my case I am running a program that is running ping as the apache user. The service is started with a uid of 0 however the apache user is not able to run ping.

an easy fix is `chmod u+s /bin/ping` however I feel like this should be something that makes it's way upstream.

To reproduce you can do build this dockerfile https://github.com/michaeljs1990/phpipam/blob/dockerfile/Dockerfile and then exec into it make a lol.php file in the working dir and use this script.

```
<?php

exec("/bin/ping 192.168.1.5 2>&1";
```

and go go lol.php.

**Comment by michaeljs1990** [comment]
P.S you will have to remove the `chmod u+s /bin/ping` which i just pushed to that dockerfile.

**Comment by michaeljs1990** [comment]
ops sorry, got confused with what repo i was in. name doesn't help :P

**Comment by six8** [comment]
I've ran into the same issue running an Alpine Docker image on an Alpine Docker host.

**Comment by sujitas400** [comment]
> Hello!
> Is that normal behaviour? what after creating container by command
> `docker run -d smebberson/docker-alpine`
> and then getting shell by
> `docker exec -it [container_id] sh`
> and send `ping 172.17.0.1` i've got a error message
> 
> > ping: permission denied (are you root?)
> 
> how can i solve this problem?
> 
> P.S. docker version 1.12.1
> 
> thank you

Add user:  root in docker-compose file

**Comment by tonyctp** [comment]
i've ran into the same issues. and maybe you could try 
`docker exec -it [container_id] --privileged sh`
all of things will be fine

**Comment by yjqg6666** [comment]
Run the following command may resolve your issue.
\# apk add --no-cache iputils && addgroup $USER ping
