### ISSUE TITLE
consul dns error

### ISSUE THREAD

**Issue by wangwj** [smebberson/docker-alpine#69]
Load average: 0.00 0.01 0.00 1/210 1697
  PID  PPID USER     STAT   VSZ %VSZ CPU %CPU COMMAND
  260   242 go-dnsma S    10576   1%   0   0% go-dnsmasq --default-resolver --ndots 1 --fwd-ndots 0 --stubzones=.consul/172.17.0.2:8600 --hostsfile=/etc/hosts
  590     0 root     S     6208   0%   3   0% bash
  242   230 root     S     1516   0%   2   0% sh ./run
 1697   590 root     R     1516   0%   0   0% top
  259   243 root     S     1512   0%   0   0% sh /usr/bin/consul-available
  243   231 root     S     1512   0%   3   0% sh ./run
 1696   259 root     S     1508   0%   2   0% sleep 1
    1     0 root     S      192   0%   3   0% s6-svscan -t0 /var/run/s6/services
  231     1 root     S      192   0%   2   0% s6-supervise consul
   31     1 root     S      192   0%   3   0% s6-supervise s6-fdholderd
  230     1 root     S      192   0%   0   0% s6-supervise resolver
bash-4.3# ls *find
container-find  find
bash-4.3# sh -x container-find
+ dig +short consul
bash-4.3# dig +short consul

dig no record

**Comment by smebberson** [comment]
What does your `/etc/hosts` and `/etc/resolv.conf` look like?

**Comment by wangwj** [comment]
@smebberson 
/etc/hosts 
127.0.0.1	localhost
::1	localhost ip6-localhost ip6-loopback
fe00::0	ip6-localnet
ff00::0	ip6-mcastprefix
ff02::1	ip6-allnodes
ff02::2	ip6-allrouters
172.17.0.2	c3bf2baaa14f

/etc/resolv.conf
nameserver 127.0.0.1 # added by go-dnsmasq
# Generated by dhcpcd from eth0.dhcp
# /etc/resolv.conf.head can replace this line
domain local
# disabled by go-dnsmasq # nameserver 192.168.65.1
# disabled by go-dnsmasq # nameserver 192.168.65.10
# disabled by go-dnsmasq # nameserver 192.168.65.9
# disabled by go-dnsmasq # nameserver 192.168.65.8
# disabled by go-dnsmasq # nameserver 192.168.65.7
# disabled by go-dnsmasq # nameserver 192.168.65.6
# disabled by go-dnsmasq # nameserver 192.168.65.5
# disabled by go-dnsmasq # nameserver 192.168.65.4
# disabled by go-dnsmasq # nameserver 192.168.65.3
# /etc/resolv.conf.tail can replace this line


dig no param  resut:

; <<>> DiG 9.10.4-P4 <<>>
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: REFUSED, id: 40939
;; flags: qr rd; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 0
;; WARNING: recursion requested but not available

;; QUESTION SECTION:
;.				IN	NS

;; Query time: 0 msec
;; SERVER: 127.0.0.1#53(127.0.0.1)
;; WHEN: Tue Dec 13 22:02:57 CST 2016
;; MSG SIZE  rcvd: 17

**Comment by wangwj** [comment]
@smebberson  top commond result:
260 242 go-dnsma S 10576 1% 0 0% go-dnsmasq --default-resolver --ndots 1 --fwd-ndots 0 --stubzones=.consul/172.17.0.2:8600 --hostsfile=/etc/hosts

seem stubzones param do not function

**Comment by wangwj** [comment]
error found ,docker run commond  start
