### ISSUE TITLE
Incorrect s6 service restart instructions

### ISSUE THREAD

**Issue by matthewvalimaki** [smebberson/docker-alpine#7]
At least README.md for alpine-nginx instructs the following to restart nginx:
```
s6-svc -h /etc/services.d/nginx
```
However this results in:
> s6-svc: fatal: unable to control /etc/services.d/nginx: No such file or directory

The correct command to restart nginx is:
```
s6-svc -h /var/run/s6/services/nginx/
```
This results in nginx worker process to be restarted.

**Comment by smebberson** [comment]
Nice catch. Whoops! It is a left over from migrating from Ubuntu to Alpine Linux. I'll get this one resolved tomorrow too.

**Comment by smebberson** [comment]
@matthewvalimaki, this has been [updated](https://github.com/smebberson/docker-alpine/tree/master/alpine-nginx). Thanks again.
