### ISSUE TITLE
alpine-base build command parameter

### ISSUE THREAD

**Issue by sabrehagen** [smebberson/docker-alpine#70]
Hi,

What is the `/vagrant/alpine-base` in the [/alpine-base/build](https://github.com/smebberson/docker-alpine/blob/master/alpine-base/build) script? There's no `alpine-base` folder in the `/vagrant` path of this repo, so I am confused as to its purpose.

Thanks

**Comment by smebberson** [comment]
Those scripts are designed to be run inside the VM, not on your host. When the VM is started, it maps the root of this repository to `/vagrant` within the VM. Then the paths line up in the build scripts.

Does that make sense?

**Comment by sabrehagen** [comment]
Yes, thank you.
