### ISSUE TITLE
Unable to use the `run` scripts in each directory under examples/

### ISSUE THREAD

**Issue by ravi-sensify** [smebberson/docker-alpine#83]
Hi, I'm unable to execute any of the `run` scripts in the `examples` directory. Am I doing something wrong? Thanks! --ravi.

![screen shot 2017-03-31 at 5 16 36 pm](https://cloud.githubusercontent.com/assets/22693975/24573297/6f48699a-1636-11e7-910e-7b8b10722b37.png)

**Comment by smebberson** [comment]
Have you tried running the `build` scripts first? Sometimes there is a `build` script, but if there is a `docker-compose.yml` file, you need to run `docker-compose build` from within that directory...

**Comment by ravi-sensify** [comment]
Yup, that did it, thank you Scott. I needed to:

```
mkdir /vagrant/
mkdir /vagrant/examples/
# checkout user-nginx into /vagrant/examples
./build
./run
```

to make it all work, since the `build` script relies on finding the code at `vagrant/examples`.

I am happy to submit a Pull Request to update the `README.md` file, and potentially fix some issues with the `build/run` scripts, if you think it is useful. Thx for putting this stuff together!

**Comment by smebberson** [comment]
Ah, I see, you're not running within Vagrant? Everything is setup and intended to be run through a Vagrant VM...

**Comment by smebberson** [comment]
@ravi-sensify, this is the guide... https://github.com/smebberson/docker-alpine/blob/master/CONTRIBUTING.md

I think I might need to improve the README though so it's more obvious...

**Comment by ravi-sensify** [comment]
Sounds good, I'll take a closer look. No, I'm ripping a bunch of dockers our for my own private use, I didn't realize individual dockers were so tightly coupled with Vagrant itself.

Thanks a ton once again! 👍

**Comment by smebberson** [comment]
@ravi-sensify, they're not really tightly coupled to Vagrant. Just the development environment and examples are.

If you're planning on using these on your own projects, it's intended that you'll download them from Docker Hub in your Dockerfile as per `FROM smebberson/alpine-rabbitmq` for example.
