### ISSUE TITLE
Unable to build alpine-base image

### ISSUE THREAD

**Issue by sramazzina** [smebberson/docker-alpine#85]
Hi,

I tried to build your alpine-base image directly on my system but I was unable to do this. At the very first try I was getting this error

_/bin/sh: setcap: not found_

and that was related to the missing on _libcap_ package from the packages set. I lightly modified your Docker file by adding the _libcap_ package to the list of packages you are installing while building the image (it seemed missing). Without adding that package to the set of installed packages the setcap binary was completely missed. After that, at the second try, I get a different error like this.

> Failed to set capabilities on file `/bin/go-dnsmasq' (Not supported) usage:
>
> setcap [-q] [-v] (-r|-|<caps>) <filename> [ ... (-r|-|<capsN>) <filenameN> ]
>
> Note <filename> must be a regular (non-symlink) file.

After further investigation I noticed that there seems [there is a problem by using setcap on systems using aufs](https://github.com/hashicorp/docker-vault/issues/19)  and unfortunately my docker system is using aufs of course. 

Therefore my question is: how can I successfully build your alpine-base image?

**Comment by bjuri** [comment]
Hi @sramazzina, you can do the trick:
1. Go to the your **custom alpine-base** dir
1. In the Dockerfile just comment part with
`setcap CAP_NET_BIND_SERVICE=+eip /bin/go-dnsmasq`
2. Like @bluen mentioned in the #80, open file
`<your alpine-base dir>/root/etc/services.d/resolver/run`
and replace all content with:
```
#!/usr/bin/with-contenv sh

RUNAS="go-dnsmasq"

setcap -v CAP_NET_BIND_SERVICE=+eip /bin/go-dnsmasq
status=$?

if [ !$status ];
then
    RUNAS="root"
fi

s6-setuidgid ${RUNAS} go-dnsmasq --default-resolver --ndots "1" --fwd-ndots "0" --hostsfile=/etc/hosts >> $GO_DNSMASQ_LOG_FILE 2>&1
# Original line
# s6-setuidgid go-dnsmasq go-dnsmasq --default-resolver --ndots "1" --fwd-ndots "0" --hostsfile=/etc/hosts >> $GO_DNSMASQ_LOG_FILE 2>&1
```

After all preparations just run ./build script.

Notes to all fellows:

> If you want to have same working behaviour in descendant images just override example images like in folder `./examples/` and do the step 2 in this comment above

**Comment by smebberson** [comment]
@sramazzina, I've just release `v3.2.0-beta.1` that contains the necessary fixes. You'll need to set the `GO_DNSMASQ_RUNAS` environment variable to `root` to get around these issues.

@bjuri, any thoughts on the more light weight solution to `setcap` issues...

**Comment by smebberson** [comment]
I just released a new version of alpine-base image. This should work fine now.

**Comment by smebberson** [comment]
This is all up and running now :)
