### ISSUE TITLE
csh shell available?

### ISSUE THREAD

**Issue by marty-sullivan** [smebberson/docker-alpine#86]
Hi, I am trying to build some legacy apps that require csh into an alpine container image, however, I cannot find the csh shell within the apk repos. Is there not a package for this shell available?

**Comment by smebberson** [comment]
@marty-sullivan, I've never tried to look for it before. I just had a quick look and no, it doesn't look like there is one. A quick Google didn't turn up much either, sorry!

Just be aware that bash isn't included by default either, so if you're looking to port them to bash you'll have to install that package.
